version: "3"
services:
  mconf-aggr-webhook:
    image: mconf/mconf-aggr:dev-latest
    ports:
      - "8000:8000"
    networks:
      - mconf-net-dev
    env_file:
      - ${MCONF_AGGR_WEBHOOK_ENV_FILE}
    volumes:
      - ./:/usr/src/mconf-aggr

networks:
  mconf-net-dev: