ARG PYTHON_VERSION
ARG BASE_PATH
ARG APP_NAME

#
# Stage: debug
#
FROM mconf-aggr-base as  debug
ARG BASE_PATH
ARG APP_NAME

WORKDIR $BASE_PATH/$APP_NAME

EXPOSE 8000 5678

ENV GEVENT_SUPPORT=True \
    POETRY_VIRTUALENVS_IN_PROJECT=false

ENTRYPOINT ["poetry", "run"]
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", \
     "--wait-for-client", "-m", "gunicorn.app.wsgiapp", "mconf_aggr.main:app", \
     "--bind=0.0.0.0:8000", "--worker-class", "gevent", "--timeout", "0"]
