ARG PYTHON_VERSION
ARG BASE_PATH
ARG APP_NAME

#
# Stage: development
#
FROM mconf-aggr-base as development
ARG BASE_PATH
ARG APP_NAME

WORKDIR $BASE_PATH/$APP_NAME

EXPOSE 8000

ENV POETRY_VIRTUALENVS_IN_PROJECT=false

ENTRYPOINT ["poetry", "run"]
CMD ["gunicorn", "mconf_aggr.main:app", "--bind=0.0.0.0:8000", \
     "--worker-class", "gevent"]
