version: "3"
services:
  mconf-aggr-webhook:
    image: mconf/mconf-aggr:webhook-latest
    ports:
      - "8000:8000"
    networks:
      - mconf-net-dev
    env_file:
      - ${MCONF_AGGR_WEBHOOK_ENV_FILE}

networks:
  mconf-net-dev:
