name: Continuous Integration

on:
  push:
    paths:
      - '**.py'
    branches: [ master, develop ]
  pull_request:
    paths:
      - '**.py'
    branches: [ master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      #
      # Preparation
      #
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.10"

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.13"

      - name: Install Dependencies
        run: |
          make install-deps

      #
      # Actual jobs
      #
      - name: Run job
        run: |
          make lint